package fsmbuilder;

/**
 * Finite-state machine builder
 * @author Zaurbek Gasanov
 */
public class FSMBuilder extends javax.swing.JFrame {

    /**
     * Creates new form FSMBuilder
     */
    public FSMBuilder() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        grammarPanel = new javax.swing.JPanel();
        grammarDefinition = new javax.swing.JLabel();
        vtLabel = new javax.swing.JLabel();
        vtTField = new javax.swing.JTextField();
        vnLabel = new javax.swing.JLabel();
        vnTField = new javax.swing.JTextField();
        sLabel = new javax.swing.JLabel();
        sTField = new javax.swing.JTextField();
        pArea = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pTArea = new javax.swing.JTextArea();
        buildMachineButton = new javax.swing.JButton();
        machineTablePanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Finite-state machine builder");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("frame"); // NOI18N

        grammarPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Регулярная грамматика"));
        grammarPanel.setToolTipText("");
        grammarPanel.setName(""); // NOI18N

        grammarDefinition.setText("<html> Регулярная грамматика <i>G = (VT, VN, P, S)</i>,<br /><b>VT</b> - алфавит терминальных символов,<br /><b>VN</b> - алфавит нетерминальных символов,<br /><b>P</b> - правила вывода,<br /><b>S</b> - начальный символ (цель). </html>");

        vtLabel.setText("VT");

        vtTField.setToolTipText("Разделяйте символы пробелами");

        vnLabel.setText("VN");

        vnTField.setToolTipText("Разделяйте символы пробелами");

        sLabel.setText("S");

        pArea.setText("P");

        pTArea.setColumns(20);
        pTArea.setRows(5);
        pTArea.setToolTipText("Каждое правило записывайте на отдельной строке");
        jScrollPane1.setViewportView(pTArea);

        buildMachineButton.setText("Построить автомат");

        javax.swing.GroupLayout grammarPanelLayout = new javax.swing.GroupLayout(grammarPanel);
        grammarPanel.setLayout(grammarPanelLayout);
        grammarPanelLayout.setHorizontalGroup(
            grammarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grammarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(grammarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(grammarDefinition, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(grammarPanelLayout.createSequentialGroup()
                        .addGroup(grammarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buildMachineButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(grammarPanelLayout.createSequentialGroup()
                                .addGroup(grammarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vtLabel)
                                    .addComponent(vnLabel)
                                    .addComponent(sLabel)
                                    .addComponent(pArea))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(grammarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vnTField)
                                    .addComponent(vtTField)
                                    .addComponent(sTField)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE))))
                        .addContainerGap())))
        );
        grammarPanelLayout.setVerticalGroup(
            grammarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grammarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(grammarDefinition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(grammarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vtLabel)
                    .addComponent(vtTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(grammarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vnLabel)
                    .addComponent(vnTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(grammarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sLabel)
                    .addComponent(sTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(grammarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(grammarPanelLayout.createSequentialGroup()
                        .addComponent(pArea)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buildMachineButton)
                .addContainerGap())
        );

        machineTablePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Конечный автомат"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout machineTablePanelLayout = new javax.swing.GroupLayout(machineTablePanel);
        machineTablePanel.setLayout(machineTablePanelLayout);
        machineTablePanelLayout.setHorizontalGroup(
            machineTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(machineTablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                .addContainerGap())
        );
        machineTablePanelLayout.setVerticalGroup(
            machineTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(machineTablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addComponent(grammarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(machineTablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(machineTablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(grammarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 104, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException |InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FSMBuilder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FSMBuilder().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buildMachineButton;
    private javax.swing.JLabel grammarDefinition;
    private javax.swing.JPanel grammarPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel machineTablePanel;
    private javax.swing.JLabel pArea;
    private javax.swing.JTextArea pTArea;
    private javax.swing.JLabel sLabel;
    private javax.swing.JTextField sTField;
    private javax.swing.JPanel topPanel;
    private javax.swing.JLabel vnLabel;
    private javax.swing.JTextField vnTField;
    private javax.swing.JLabel vtLabel;
    private javax.swing.JTextField vtTField;
    // End of variables declaration//GEN-END:variables
}
